#!/bin/bash

# Set the path to the deployment directory
DEPLOYMENT_PATH="$(pwd)/deployment/opentofu"

# Echo the deployment path for debugging purposes
echo "Deployment path: $DEPLOYMENT_PATH"

# Function to initialize and apply tofu configuration in a given directory
tofu_apply() {
    local dir=$1
    echo "Processing directory: $dir"
    
    if [ -d "$dir" ]; then
        cd "$dir" || { echo "Failed to change directory to $dir"; exit 1; }
        
        echo "Running tofu init in $dir"
        tofu init || { echo "tofu init failed in $dir"; exit 1; }

        echo "Running tofu apply in $dir"
        tofu apply --auto-approve || { echo "tofu apply failed in $dir"; exit 1; }

        echo "##################################"
    else
        echo "Directory $dir does not exist. Skipping."
    fi
}

# Apply tofu configuration in the required directories
tofu_apply "$DEPLOYMENT_PATH/requirements"
tofu_apply "$DEPLOYMENT_PATH/monitoring"
tofu_apply "$DEPLOYMENT_PATH/fastapi"

echo "Deployment process completed successfully!"


echo "The password of the grafana UI"
kubectl get secret --namespace monitoring loki-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo